spring:
  application:
    name: Sport_app_android_vkr
  liquibase:
    enabled: false
    change-log: liquibase/master.xml
  datasource:
    url: jdbc:postgresql://localhost:5435/coffee_db
    username: postgres
    password: postgres
    generate-unique-name: false
  security:
    user:
      name: user
      password: password

server:
  port: 8081
